### ISSUE TITLE
Command line build scripts for osx improvements for El Capitan / Arduino > 1.5

### ISSUE THREAD

**Issue by ewidance** [synthetos/g2#142]
On TinyG2-OSX-Programmer, directories  refers to old Arduino arch (< 1.5). 
DueFromOSX.sh  must be adapted to reflect Arduino architecture change 

```
...
arduinoLibDir=~/Library/Arduino15/
PATH=$PATH:$arduinoLibDir/packages/arduino/tools/arm-none-eabi-gcc/*/bin/:$arduinoLibDir/packages/arduino/tools/
...
...
echo "Starting programming of file ${file} -> ${file/.elf/.bin} on port ${port/\/dev\//}"
$arduinoLibDir/packages/arduno/tools/bossac/*/bossac -e -w -v -b "${file/.elf/.bin}"

```

Additionnaly, a small change in TinyG2/platform/atmel_sam-flash.sh  alllows use of first usbmodem active port found on system :

```
...
../Resources/TinyG2-OSX-Programmer/DueFromOSX.sh -f "${1}" -p /dev/tty.usbmodem*
...
```

Not a bit deal, but small improvement...

**Comment by justinclift** [comment]
Thanks for this @ewidance.  Sorry for the really long delay.

With the script for using the Due from OSX, that should be fixed already in the [edge branch](https://github.com/synthetos/g2/blob/2337102e71de9d9eb29fea6405365915dc2475a2/Resources/TinyG2-OSX-Programmer/DueFromOSX.sh#L60-L80) version. :smile:

With the 2nd bit... the file `atmel_sam-flash.sh` doesn't seem to exist (any more).  At a guess, it's probably something that used to exist back when this issue was created, but has subsequent been dropped.

Going to close this, as there doesn't seem to be any action we need to take on any bits in it.

As a data point with g2core, future reported issues will probably be looked at a lot quicker than the ~2 year delay on this one. :smile:
