### ISSUE TITLE
Question on feedrate config values

### ISSUE THREAD

**Issue by DeanCavaliere** [synthetos/g2#458]
Depending on which settings_<machine name> you look at on here, you can see different values of things like jerk, feedrate, velocity, etc etc. The values of x and y are typically exactly the same but z is usually different. For example, in settings_shapeoko2dual, the x axis has a velocity/feedrate of 50000 while the z axis has a value of 1200. 
Why is this? is there a relationship between these values so that the x/y and z axis all move at the same relative speeds in reality? or can these values be arbitrarily chosen?

![image](https://user-images.githubusercontent.com/49283626/76638087-41798d80-6522-11ea-9f0e-794f1608a347.png)

**Comment by justinclift** [comment]
It's a "maximum" feed rate, and - for me at least - I tend to set it to what the machine seems happy with on that particular axis.

eg see how fast any particular axis seems to move in a reliable  + repeatable fashion, then set the feed rate maximum for that axis to that value

The difference of X & Y axis feedrates compared to Z axis is probably due to different tech being used on the example settings.  For example, it's pretty common to have belt driven motors run the X and Y axis, with the Z axis being ball screw driven.  Belt driven setups seem to have much higher potential feed rates than ball screws.  So, there's generally a difference there.

Does that help? :smile:

**Comment by DeanCavaliere** [comment]
Yes that helps so much; I got the impression there might've been a relationship due to the different modes of travel being used but if it's just dependent on machine performance then perfect. Thank you so much man

**Comment by justinclift** [comment]
You're welcome @DeanCavaliere. :smile:
